### ISSUE TITLE
Aid Effect not Triggering Modifiers Matter

### ISSUE THREAD

**Issue by ChaseDonnally** [shemetz/pf2e-modifiers-matter#22]
The Aid effect isn't getting highlighted when it's the effect that tips a check into the next degree of success. I know this used to work, as I'd configured a specific animation for it. I'm not sure what happened that caused it to stop being picked up. I've confirmed other bonuses are highlighting green as expected within this world. Screenshots included. Thanks for your work on this module!

![image](https://github.com/shemetz/pf2e-modifiers-matter/assets/47797620/f52826cd-d3cb-45c8-828e-fb9c289c4362)
![image](https://github.com/shemetz/pf2e-modifiers-matter/assets/47797620/e1c2078c-6aa3-43ba-8a2d-8b6ce247654f)

Example of Modifiers Matter working:
![image](https://github.com/shemetz/pf2e-modifiers-matter/assets/47797620/08c14dc9-e43d-4684-bc0f-e78d500d1bb1)

**Comment by shemetz** [comment]
The error wasn't with Aid, it was with targeting AC.  Same issue as in #23.  Fixed for next release, v1.7.6
