### ISSUE TITLE
Support for PF2 5.4

### ISSUE THREAD

**Issue by git-kor-av** [shemetz/pf2e-modifiers-matter#28]
In addition to the error associated with 5.3 reported here:  https://github.com/shemetz/pf2e-modifiers-matter/issues/26

It appears that all modifier highlighting is no longer working in 5.4, here is an example where I would have expected some green highlighting due to Heroism and/or Aid:
![image](https://github.com/shemetz/pf2e-modifiers-matter/assets/32276185/189fa223-95e2-4256-8410-0dc6fb65ffa7)

**Comment by shemetz** [comment]
Fixed in v1.7.8
