### ISSUE TITLE
Console Error on Reroll with Hero Point

### ISSUE THREAD

**Issue by ottyn** [shemetz/pf2e-modifiers-matter#29]
Foundry VTT 11.311
PF2e 5.6.1
Modifiers Matter 1.8.1

Error popped up in console during a combat when an attack card was right-clicked on and "Reroll with Hero Point" was selected.  Attack was re-rolled correctly and chat card was updated.

![modifiers_matter](https://github.com/shemetz/pf2e-modifiers-matter/assets/97130150/9a241dda-0ab4-47c2-96d4-8bf5aae0a3ea)

**Comment by shemetz** [comment]
Fixed in v1.8.2 + added handling of rerolled rolls!  Now the module will actually correctly highlight modifiers after a reroll

**Comment by shemetz** [comment]
Oops, this was bugged until 1.8.6
