### ISSUE TITLE
Conflict with the new "Show Roll Breakdowns" option in 5.12

### ISSUE THREAD

**Issue by Ghostdesu** [shemetz/pf2e-modifiers-matter#33]
The option is disabled by default, which hides all modifiers and dice rolls that npcs make from players. 

With this new default behavior, the Modifiers Matter module fails to properly display the relevant modifiers to the players, instead only highlighting it on GM's view. 

Ideally, the module should "unhide" the highlighted elements so the players can see them as well.

**Comment by Ghostdesu** [comment]
GM View
![image](https://github.com/shemetz/pf2e-modifiers-matter/assets/31375910/11eed1f5-7aeb-4b35-940b-be4aa9fb839a) 

Player View
![image](https://github.com/shemetz/pf2e-modifiers-matter/assets/31375910/a7cbac6f-52bd-432b-9107-0bdb40576066)

**Comment by Ghostdesu** [comment]
Following some additional testing, the issue seems to only affect ranked prepared spells with spontaneous ones correctly heightening damage

**Comment by shemetz** [comment]
Fixed in v1.9.0
