### ISSUE TITLE
 Module currently doesn't color the modifiers correctly when using PF2E Pathfinder UI v3

### ISSUE THREAD

**Issue by SAOFan4Ever** [shemetz/pf2e-modifiers-matter#37]
I'm having an issue when using Modifiers Matter with PF2E Pathfinder UI v3. The modifiers effecting the outcome turn gray making it hard to tell the difference. Not sure why the colors aren't working.

Anyways, great module keep up the good work. Let me know if you need anymore info.

UI ON

![Screenshot (14)](https://github.com/shemetz/pf2e-modifiers-matter/assets/142608632/67f42a64-a5bb-4bea-a68f-ec8dd7562065)

UI OFF:

![Screenshot (15)](https://github.com/shemetz/pf2e-modifiers-matter/assets/142608632/760653c0-4e6c-4b4b-8c7e-13c43c3c2ae0)

Module List

Note: I checked the "Disable Pathfinder UI" in the PF2E UIv3 settings menu that is why it is checked in the screenshot below.

![Screenshot (16)](https://github.com/shemetz/pf2e-modifiers-matter/assets/142608632/86d80830-5104-4870-adb9-ac7b64fbff95)

**Comment by SAOFan4Ever** [comment]
I spoke with the Pathfinder  UI creator. They said that there is not be much they can do since Modifiers Matter uses some of the same interface code to modify the UI. If there is nothing that can be done about it you might want to list the Pathfinder UI v3 as a conflict for now.

**Comment by SAOFan4Ever** [comment]
Sasmira was able to modify the Modifiers Matter CSS file to seemingly fix the above issue. I'm going to provide it here in case in can help you. Although they said they are going to incorporate the fix in the code. Not sure exactly how. The only minor issue I have is that the dark green text is still a little bit hard to read but not a huge deal. Would it be possible to add color pickers to the module settings? That way  users the choose the colors that work best for them.

![Screenshot (22)](https://github.com/shemetz/pf2e-modifiers-matter/assets/142608632/803f7efa-b7ca-4ded-9aad-c058d1f9e47f)
 
[pf2e-modifiers-matter-workaound.zip](https://github.com/shemetz/pf2e-modifiers-matter/files/15259107/pf2e-modifiers-matter-workaound.zip)

**Comment by shemetz** [comment]
Wonderful, I love it when things get resolved while I'm on break :)

Thanks for including so much information!  <3
