### ISSUE TITLE
Feature Request: integrate with PF2e Toolbelt's Target Helper saving throws

### ISSUE THREAD

**Issue by poindexter1985** [shemetz/pf2e-modifiers-matter#38]
I brought this up in the Toolbelt thread on the PF2e Foundry Discord - saving throws rolled using Toolbelt's target helper functionality don't send a message to the chat log, so Modifiers Matter never gets a chance to highlight the modifiers that matters.

You and Idle discussed this briefly, and you asked that an issue be created to help you remember to look into this further.

Link to the start of the conversation: https://discord.com/channels/880968862240239708/1161247098176553072/1237464596055330907

**Comment by shemetz** [comment]
API added to pf2e-modifiers-matter version 1.9.2

**Comment by shemetz** [comment]
@reonZ - let me know if you want/need more from the API.
